### PR TITLE
Fix panic out of range when index map gets out of sync with normalization text

### LINKED ISSUE #26: bug: panic with index out of range when characters increase in size by ToLower()
In two different locations of normalizer:replaceMatchesWithStringsAndUpdateIndexMap() (line numbers vary by version) an index out of range error will happen when the NormalizedText increases in length after the IndexMap is created (and the IndexMap isn't adjusted.  An example of the error output is below.

This is happening when we encounter special characters that increase in length on ToLower().

---

panic: runtime error: index out of range [2075] with length 2072

goroutine 592509 [running]:
github.com/IBM/license-scanner/normalizer.(*NormalizationData).replaceMatchesWithStringsAndUpdateIndexMap(0xc000f39750, {0xc001ae2000?, 0xfb, 0x81c?}, {0xc001ae1000, 0xfb, 0x0?})
	/Users/markstur/go/src/github.com/ibm/license-scanner/normalizer/normalizer.go:559 +0x725
github.com/IBM/license-scanner/normalizer.(*NormalizationData).replaceMatchesWithStringAndUpdateIndexMap(0xc000f39750, {0xc001ae2000?, 0xfb, 0x155}, {0x141da08, 0x1})
	/Users/markstur/go/src/github.com/ibm/license-scanner/normalizer/normalizer.go:513 +0x226
github.com/IBM/license-scanner/normalizer.(*NormalizationData).regexpReplacePatternAndUpdateIndexMap(0xc000f39750, 0xa22?, {0x141da08, 0x1})
	/Users/markstur/go/src/github.com/ibm/license-scanner/normalizer/normalizer.go:291 +0xe8
github.com/IBM/license-scanner/normalizer.(*NormalizationData).replaceWhitespace(0xc000f39750?)
	/Users/markstur/go/src/github.com/ibm/license-scanner/normalizer/normalizer.go:481 +0x31

### PR DESCRIPTION
**Pull request by markstur**
Create IndexMap after ToLower(). Ensure this and initialize() are only done once. Protect from out of range.

Index out of range errors can happen when the Normalized Text gets longer than the IndexMap. This was happening when ToLower() was increasing the size of NormalizedText after the IndexMap creation. Initialize was also resetting NormalizedText when called after normalization shrunk the text to "".

* ToLower() is now part of initialize()
* initialize is now only called once, as needed, protected by sync.
* The out of range exposures are also now protected.
* ToLower() is now before some matchers that were using unnecessary case-insensitive matching. Those are now optimized to assume lower.

Fixes #26

Signed-off-by: Mark Sturdevant <mark.sturdevant@ibm.com>

### CODE REVIEW

File: normalizer/normalizer.go [hunk 1]
```diff
@@ -12,23 +12,24 @@ import (
...
+	"sync"
 
 	"github.com/mrutkows/sbom-utility/log"
 	"golang.org/x/exp/slices"
 )
 
 const (
-	NoteTagPattern          = `(?i)<<note[:=].+?>>`
-	WildcardMatchingPattern = `(?i)<<match=\.\+>>`
+	NoteTagPattern          = `<<note[:=].+?>>`
```
Comment (pritidesai) [inline normalizer/normalizer.go:22]: I have started reviewing changes in this PR but haven't looked at any changes down in this PR. Most of these changes are removing the clause - `case insensitive`. How are we handling it? Converting the input text to all lower/upper case?

File: normalizer/normalizer.go [hunk 2]
```diff
@@ -173,9 +170,6 @@ func (n *NormalizationData) NormalizeText() error {
 	// Replace the optional tags with <<omitable>> and <</omitable>>. (Guideline 2.1.4)
 	n.standardizeOmitableTags()
 
-	// Convert the input text to all lower case. (Guideline 4.1.1)
```
Comment (pritidesai) [inline normalizer/normalizer.go:176]: 🤔

File: normalizer/normalizer.go [hunk 3]
```diff
@@ -542,26 +544,26 @@ func (n *NormalizationData) replaceMatchesWithStringsAndUpdateIndexMap(allSubmat
...
+			replacementIndex := make([]int, replacementLen)
+			for i := 0; i < cap(replacementIndex); i++ {
+				replacementIndex[i] = -1
+			}
+			if firstIndex < len(n.IndexMap) {
+				replacementIndex[0] = n.IndexMap[firstIndex]
+			}
+			if replacementLen > 1 && lastIndex-1 < len(n.IndexMap) {
+				replacementIndex[replacementLen-1] = n.IndexMap[lastIndex-1]
 			}
```
Comment (pritidesai) [inline normalizer/normalizer.go:567]: Sounds good, making sure not hitting out of bound before accessing the index map.

File: normalizer/normalizer_test.go [hunk 4]
```diff
@@ -84,6 +84,24 @@ func TestNormalizationData_NormalizeText(t *testing.T) {
...
+		},
+		{
+			name: "Character that changes length should not cause out-of-bounds with indexMap (char 0)",
+			n: &NormalizationData{
+				OriginalText: "\xfe\nx\n",
+			},
+			e: &NormalizationData{
+				NormalizedText: "x",
+			},
+		},
```
Comment (pritidesai) [inline normalizer/normalizer_test.go:104]: NIT: we could add more tests such as adding a character before that special character ("x�\nx\n"): 

```
			name: "Character that changes length should not cause out-of-bounds with indexMap (char 0)",
			n: &NormalizationData{
				OriginalText: "x\xfe\nx\n",
			},
			e: &NormalizationData{
				NormalizedText: "x x",
			},
```

**Review by pritidesai — APPROVED** [review]
thank you @markstur

**Comment by pritidesai** [comment]
thank you @markstur 👍

Please add comments for any code change so that its easier to understand!
